name: Test Cases

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requierements.txt
        pytest

    - name: Run pytest
      run: |
        pytest

    - name: Additional CI/CD steps
      run: |
        # Add additional CI/CD steps here
